# Generated by Django 3.1.2 on 2020-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackyjm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='height',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weight',
            field=models.IntegerField(default=45),
        ),
    ]
